# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
rogue: rogue
markdown: kramdown
disqus: lunacuantica
google_analytics: UA-78414303-7
title: luna cuantica

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: lunacuantica

description: Blog del mundo cuantico
disqus: dbyll-ghost # add disqus short name here
author:
  name: Paulina Luna
  email: dbyll@ismaildemirbilek.com
 # github: edersix
 # twitter: edersix
 # pinterest: asd123
 # linkedin: asd123
  bio: Lic en TI, MGTIC en progreso
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://blog.mundocuantico.com
# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

gems:
  - jekyll-paginate
